apiVersion: v1
kind: Service
metadata:
  name: node-template # Replace all with application name
spec:
  selector:
    app: node-template
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-template
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-template
  template:
    metadata:
      labels:
        app: node-template
    spec:
      containers:
        - name: app
          image: luizfelipem/node-template-js:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: PG_URL
              value: 'mongodb://mongo:27017/dev'
            - name: PORT
              value: '3000'
          imagePullPolicy: Always